apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2
  labels:
    app: task2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task2
  
  template:
    metadata:
      labels:
        app: task2
    
    spec:
      containers:
      - name: task1
        image: task1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: task2
spec:
  selector:
    app: task2
  type: LoadBalancer
  ports:
  - name: main
    protocol: TCP
    port: 8002
    targetPort: 8002
    nodePort: 30001
